"""Curated NHAI / MoRTH highway project dataset.

Source attribution: data.gov.in — NHAI Awarded Projects / BharatMala Pariyojana /
MoRTH Annual Report. These are real, publicly disclosed projects. Lat/lng below
points to a representative node on the corridor (typically the project's major
city/junction) so it can be rendered on the developments map.

This file mirrors the structure of a CSV/JSON pull we would do from data.gov.in;
when an API endpoint is wired up in Phase 2.5, swap this static list for a
live fetch — the ingest pipeline downstream stays unchanged.
"""

NHAI_PROJECTS = [
    {"external_id": "NHAI-NE4", "name": "Delhi–Mumbai Expressway (NE-4)",
     "status": "Under Construction", "length_km": 1386, "investment_inr_cr": 98000,
     "completion_year": 2026, "lat": 26.8467, "lng": 75.5000, "city": "Delhi NCR",
     "submarket": "Sohna–Dausa–Ratlam Corridor",
     "description": "8-lane greenfield expressway connecting Delhi and Mumbai; world's longest under construction."},
    {"external_id": "NHAI-SAMR", "name": "Samruddhi Mahamarg (Mumbai–Nagpur)",
     "status": "Operational", "length_km": 701, "investment_inr_cr": 55000,
     "completion_year": 2025, "lat": 19.7515, "lng": 75.7139, "city": "Mumbai (MMR)",
     "submarket": "Nashik–Aurangabad Corridor",
     "description": "Hindu Hrudaysamrat Balasaheb Thackeray Maharashtra Samruddhi Mahamarg — 6-lane access-controlled."},
    {"external_id": "NHAI-NE7", "name": "Bangalore–Chennai Expressway (NE-7)",
     "status": "Under Construction", "length_km": 262, "investment_inr_cr": 17000,
     "completion_year": 2025, "lat": 12.9716, "lng": 77.5946, "city": "Bengaluru",
     "submarket": "Hoskote–Bangarapet",
     "description": "Greenfield 4-lane expressway reducing travel to 2–2.5 hrs."},
    {"external_id": "NHAI-NE2", "name": "Eastern Peripheral Expressway (NE-2)",
     "status": "Operational", "length_km": 135, "investment_inr_cr": 11000,
     "completion_year": 2018, "lat": 28.6800, "lng": 77.4500, "city": "Delhi NCR",
     "submarket": "Kundli–Ghaziabad–Palwal",
     "description": "India's first smart and green highway bypassing Delhi."},
    {"external_id": "NHAI-DWX", "name": "Dwarka Expressway (NH-248BB)",
     "status": "Under Construction", "length_km": 29, "investment_inr_cr": 9000,
     "completion_year": 2026, "lat": 28.5021, "lng": 77.0890, "city": "Delhi NCR",
     "submarket": "Dwarka–Gurugram",
     "description": "8-lane access-controlled urban expressway linking Delhi & Gurugram."},
    {"external_id": "NHAI-GANGA", "name": "Ganga Expressway",
     "status": "Under Construction", "length_km": 594, "investment_inr_cr": 36230,
     "completion_year": 2025, "lat": 26.8467, "lng": 80.9462, "city": "Delhi NCR",
     "submarket": "Meerut–Prayagraj",
     "description": "India's longest expressway under construction; 6-lane expandable to 8."},
    {"external_id": "NHAI-PURVA", "name": "Purvanchal Expressway",
     "status": "Operational", "length_km": 341, "investment_inr_cr": 22500,
     "completion_year": 2021, "lat": 26.7606, "lng": 83.3732, "city": "Delhi NCR",
     "submarket": "Lucknow–Ghazipur",
     "description": "6-lane access-controlled (expandable to 8) connecting Lucknow to Ghazipur."},
    {"external_id": "NHAI-BUND", "name": "Bundelkhand Expressway",
     "status": "Operational", "length_km": 296, "investment_inr_cr": 14716,
     "completion_year": 2022, "lat": 25.4358, "lng": 81.8463, "city": "Delhi NCR",
     "submarket": "Chitrakoot–Etawah",
     "description": "4-lane (expandable to 6) connecting Bundelkhand to Agra–Lucknow Expressway."},
    {"external_id": "NHAI-DDE", "name": "Delhi–Dehradun Expressway",
     "status": "Under Construction", "length_km": 210, "investment_inr_cr": 11000,
     "completion_year": 2025, "lat": 28.7041, "lng": 77.1025, "city": "Delhi NCR",
     "submarket": "Akshardham–Dehradun",
     "description": "6-lane elevated stretch over Rajaji Tiger Reserve — wildlife corridor design."},
    {"external_id": "NHAI-LKE", "name": "Lucknow–Kanpur Expressway",
     "status": "Under Construction", "length_km": 63, "investment_inr_cr": 4733,
     "completion_year": 2025, "lat": 26.8467, "lng": 80.9462, "city": "Delhi NCR",
     "submarket": "Lucknow–Unnao–Kanpur",
     "description": "6-lane greenfield expressway reducing Lucknow–Kanpur travel to 45 min."},
    {"external_id": "NHAI-NH152D", "name": "Trans-Haryana Expressway (NH-152D)",
     "status": "Operational", "length_km": 227, "investment_inr_cr": 10000,
     "completion_year": 2022, "lat": 29.6857, "lng": 76.9905, "city": "Delhi NCR",
     "submarket": "Ambala–Narnaul",
     "description": "Greenfield 6-lane access-controlled corridor — part of Bharatmala Phase-I."},
    {"external_id": "NHAI-MTHL", "name": "Mumbai Trans-Harbour Link (Atal Setu)",
     "status": "Operational", "length_km": 22, "investment_inr_cr": 17840,
     "completion_year": 2024, "lat": 18.9750, "lng": 72.9700, "city": "Mumbai (MMR)",
     "submarket": "Sewri–Nhava Sheva",
     "description": "India's longest sea bridge; cuts Mumbai–Navi Mumbai commute to 20 min."},
    {"external_id": "NHAI-MPE", "name": "Mumbai–Pune Expressway Capacity Augmentation",
     "status": "Under Construction", "length_km": 95, "investment_inr_cr": 6695,
     "completion_year": 2026, "lat": 18.7515, "lng": 73.4063, "city": "Mumbai (MMR)",
     "submarket": "Khopoli–Lonavala bypass",
     "description": "8-lane augmentation reducing Mumbai–Pune travel time by ~30 min."},
    {"external_id": "NHAI-CCBMR", "name": "Chennai–Bangalore–Mysuru Economic Corridor",
     "status": "Approved", "length_km": 408, "investment_inr_cr": 19000,
     "completion_year": 2028, "lat": 13.0827, "lng": 80.2707, "city": "Chennai",
     "submarket": "Chennai–Hosur–Mysuru",
     "description": "6-lane Bharatmala Phase-I greenfield corridor."},
    {"external_id": "NHAI-BMR-STRR", "name": "Satellite Town Ring Road (STRR), Bengaluru",
     "status": "Under Construction", "length_km": 281, "investment_inr_cr": 17030,
     "completion_year": 2026, "lat": 12.9716, "lng": 77.5946, "city": "Bengaluru",
     "submarket": "Dobaspet–Hoskote–Magadi",
     "description": "6-lane access-controlled satellite ring around Bengaluru."},
    {"external_id": "NHAI-NH66", "name": "NH-66 Mumbai–Kanyakumari Widening",
     "status": "Under Construction", "length_km": 1622, "investment_inr_cr": 41000,
     "completion_year": 2027, "lat": 19.0760, "lng": 72.8777, "city": "Mumbai (MMR)",
     "submarket": "Konkan Coastal Corridor",
     "description": "4 to 6-lane widening of coastal NH-66 across Maharashtra, Goa, Karnataka, Kerala, TN."},
    {"external_id": "NHAI-HYD-ORR", "name": "Hyderabad Regional Ring Road (RRR)",
     "status": "Approved", "length_km": 338, "investment_inr_cr": 17200,
     "completion_year": 2028, "lat": 17.3850, "lng": 78.4867, "city": "Hyderabad",
     "submarket": "Outer ring around Hyderabad ORR",
     "description": "Greenfield 8-lane regional ring road; planned 5–10 km outside ORR."},
    {"external_id": "NHAI-PUNE-RING", "name": "Pune Ring Road",
     "status": "Under Construction", "length_km": 173, "investment_inr_cr": 26000,
     "completion_year": 2027, "lat": 18.5204, "lng": 73.8567, "city": "Pune",
     "submarket": "Pune Inner & Outer Ring",
     "description": "6-lane access-controlled ring road — MSRDC executing in 2 phases."},
    {"external_id": "NHAI-CHN-PRR", "name": "Chennai Peripheral Ring Road",
     "status": "Under Construction", "length_km": 133, "investment_inr_cr": 12300,
     "completion_year": 2026, "lat": 13.0827, "lng": 80.2707, "city": "Chennai",
     "submarket": "Ennore–Mamallapuram",
     "description": "6-lane greenfield bypassing Chennai metropolitan area."},
    {"external_id": "NHAI-HYD-RGI", "name": "NH-44 Hyderabad–Nagpur 6-laning",
     "status": "Under Construction", "length_km": 503, "investment_inr_cr": 14800,
     "completion_year": 2026, "lat": 17.3850, "lng": 78.4867, "city": "Hyderabad",
     "submarket": "Hyderabad–Adilabad–Nagpur",
     "description": "Bharatmala 6-laning under DBFOT model."},
    {"external_id": "NHAI-VBE", "name": "Vadodara–Mumbai Expressway (Spur of NE-4)",
     "status": "Under Construction", "length_km": 379, "investment_inr_cr": 31000,
     "completion_year": 2026, "lat": 19.0760, "lng": 72.8777, "city": "Mumbai (MMR)",
     "submarket": "Vasai–Virar–Vadodara",
     "description": "8-lane access-controlled spur connecting Mumbai to Delhi–Mumbai Expressway."},
    {"external_id": "NHAI-AME", "name": "Ahmedabad–Mumbai Expressway",
     "status": "Approved", "length_km": 510, "investment_inr_cr": 32000,
     "completion_year": 2028, "lat": 19.0760, "lng": 72.8777, "city": "Mumbai (MMR)",
     "submarket": "Surat–Vapi–Virar",
     "description": "Planned 8-lane greenfield corridor (separate from DME spur)."},
    {"external_id": "NHAI-NH-CHN-OMR", "name": "Chennai OMR Widening (NH-32)",
     "status": "Under Construction", "length_km": 36, "investment_inr_cr": 3500,
     "completion_year": 2026, "lat": 12.9010, "lng": 80.2279, "city": "Chennai",
     "submarket": "OMR (Old Mahabalipuram Road)",
     "description": "6-laning of Chennai's IT corridor connecting Sholinganallur to Mahabalipuram."},
    {"external_id": "NHAI-NH7-PUN", "name": "Pune–Bengaluru Expressway",
     "status": "Approved", "length_km": 700, "investment_inr_cr": 50000,
     "completion_year": 2028, "lat": 18.5204, "lng": 73.8567, "city": "Pune",
     "submarket": "Pune–Solapur–Bengaluru",
     "description": "Planned 8-lane greenfield Bharatmala Phase-II corridor."},
    {"external_id": "NHAI-RAIPUR-VIZAG", "name": "Raipur–Vishakhapatnam Economic Corridor",
     "status": "Under Construction", "length_km": 464, "investment_inr_cr": 24000,
     "completion_year": 2027, "lat": 17.6868, "lng": 83.2185, "city": "Hyderabad",
     "submarket": "Raipur–Vizag–Hyderabad",
     "description": "Bharatmala Phase-I 6-lane corridor reducing travel time by 50%."},
]
